name: Build e Push Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build da imagem
        run: docker build -t luigiizzo4/app-cicd-projeto-dio:1.0 ./app

      - name: Push da imagem
        run: docker push luigiizzo4/app-cicd-projeto-dio:1.0